# Generated by Django 4.2.7 on 2024-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0003_remove_job_job_file_job_english_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='english_job_description',
            field=models.FileField(blank=True, default=None, null=True, upload_to='english_job_description_file/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='french_job_description',
            field=models.FileField(blank=True, default=None, null=True, upload_to='french_job_description_file/'),
        ),
    ]
